Authentication
WailGree/remail-frontend pull request #2
Opened 2021-02-24 12:18 UTC by mateszathmari

2021-02-24 13:30 UTC, fatamorgana95 approved these changes

2021-02-25 09:19 UTC, WailGree requested changes
Remove commented, unused code. (LoginPage.js line 12, Narbar.js line 12)

2021-02-25 09:21 UTC, fatamorgana95 requested changes
Remove dead code.

2021-02-25 09:28 UTC, WailGree approved these changes
Noice

2021-02-25 09:28 UTC, fatamorgana95 approved these changes

2021-02-25 09:29 UTC, merged